### ISSUE TITLE
missing doc for report type collection methods

### ISSUE THREAD

**Issue by tedphillips** [IBM/paxapi#12]
the accessors on the report collections are not always straightforward, i've seen a few cases where consumers [understandably] did not get the right call pattern.

**Comment by tedphillips** [comment]
will put the gaps as a series of comments on this item.

will start with some for explorations.

```
Reporting.Explorations
   Count - count of explorations in active book
   GetAt(sheet) - gets the exploration object on specified sheet name from the active book if it exists.
   GetReports() - gets the collection of exploration objects from the active book
```

**Comment by tedphillips** [comment]
```
Reporting.QuickReports
     Count - count of Quick Reports in active book
     GetReports() - gets the collection of quick report objects from active book

```

**Comment by tedphillips** [comment]
```
Reporting.DynamicReports
      GetReports() - gets the collection of dynamic report objects from active book
      GetAt(sheet) - gets the collection of dynamic report objects from the specified sheet name in the active book
      Get(ignored, sheet, id) - gets the dynamic report object from the specified sheet name with the given ID in the active book
```

**Comment by tedphillips** [comment]
also, I think we need to clean up mentions of 'Reporting.GetCurrentReport' in the sample with equivalents from these lists, I don't believe that works across the 3 relevant reporting types.

**Comment by charliele** [comment]
Explorations:
https://ibm.github.io/paxapi/#exploration-api-functions

QR:
https://ibm.github.io/paxapi/#quick-report-api-functions

DR:
https://ibm.github.io/paxapi/#dynamic-report-api-function

**Comment by tedphillips** [comment]
great start! let's stop there for now and see how feedback goes.
