### ISSUE TITLE
Unlink api showing message

### ISSUE THREAD

**Issue by lieslberry** [IBM/paxapi#14]
Operating system: ✍️ TODO
Last upstream commit (run `git log --author="Robert Lord" | head -n 1`): ✍️ TODO
Browser version(s): ✍️ TODO
Ruby version (run `ruby -v`):  ✍️ TODO

---

✍️ TODO write your issue here
When I am using the UnlinkSheet VBA script, I get a message if I am sure to convert to a snapshot. After suppressing the message the snapshot does not occur.

**Comment by tedphillips** [comment]
A recent PA for Excel update changes the 'default' answer to unlink actions when prompts are suppressed to proceed.  I would also encourage setting Excel Application.displayAlerts = false, which we've integrated into the addin-message suppression system during automation.

**Comment by tedphillips** [comment]
please retry with SC56 or SC57
