### ISSUE TITLE
RefreshAllDataAndFormat results in Error

### ISSUE THREAD

**Issue by FilipSuster** [IBM/paxapi#15]
Hello,

in my VBA code I was trying to save some effort for the users and refresh Quick reports in the Workbook for them (so that they don't have to click the Refresh button ![image](https://user-images.githubusercontent.com/71491725/93738413-039ea580-fbe6-11ea-94a5-ed9b3731f476.png)  ).

This is the code line that I have added
![image](https://user-images.githubusercontent.com/71491725/93738500-3a74bb80-fbe6-11ea-89f3-d1e0ff01d77c.png)

but it doesn't work and it gives me this error message:
_Cognos.Office.Tm1.Connections.ExecuteQueryCellSetException: Při provádění kódu MDX došlo k chybě: SELECT:  Could not construct view array 

   at Cognos.Office.Tm1.OData.Providers.ODataMdxQueryProvider.Execute(MdxQueryParameters args)
   at Cognos.Office.Tm1.MdxQueryProvider.ExecuteQuery(MdxQueryParameters qp)
   at Cognos.Office.Tm1.Tm1DataProvider.ExecuteRequestInfo(IQuerySpec query, RequestInfo rs, ExecuteOptionsEnum actions, CancellationToken cancelToken)
   at Cognos.Office.Tm1.Tm1DataProvider.Execute(IQuerySpec query, ExecuteOptionsEnum actions, CancellationToken cancelToken)
   at Cognos.Office.Reporting.DataSource.Query.ConnectedReport.GenerateRender_DoWork(RunRequest request, CancellationToken cancel)
   at Cognos.Office.Framework.Threading.Tasks.PoolTask`3.Invoke()
   at Cognos.Office.Framework.Threading.Tasks.AsyncTask.Run()_

Interestingly enough, when I refresh the workbook manually by clicking the mentioned button, everything works fine, I receive no errors. So obviously the "CognosOfficeAutomationObject.RefreshAllDataAndFormat" is not equal to what happens when the user clicks the refresh button. Can you help me with this? What code is exactly behind the refresh button? Thank you

**Comment by tedphillips** [comment]
need to know about more about your use case. 

the codepath is shared, but i'm unclear on what the working state of your ribbon is - is it in the 'All' position? if so, then the api call should match very closely, at least in successful cases.

I would believe that error handling pattern is a bit different than the interactive refresh vs programmatic, the trace you've posted is from a background thread so it doesn't give full insight into what went wrong. More detail can be capture using the PA for Excel logging.

**Comment by FilipSuster** [comment]
Ok I think the problem was probably caused because I was trying to connect to some data that I didn't have access to. But still you say that the "CognosOfficeAutomationObject.RefreshAllDataAndFormat" does not entirely match the Refresh button in the IBM Ribbon? Is there a way to edit the mentioned VBA line to refresh only one sheet or entire workbook? Thank you for your reply

**Comment by tedphillips** [comment]
All is all, so for _any_ open books in some regards.

the Reporting object APIs offer book and sheet scoped activities.

https://ibm.github.io/paxapi/#refreshbook
https://ibm.github.io/paxapi/#refreshsheet

**Comment by tedphillips** [comment]
i think i answered the remaining question about scope controlled alternative endpoints, but otherwise let us know if there is an outstanding concern.
