### ISSUE TITLE
Improvement of example syntax for Publish function

### ISSUE THREAD

**Issue by ericweissbrich** [IBM/paxapi#28]
**Bug Description**
The [example syntax ](https://github.com/IBM/paxapi/blob/master/source/includes/globalapi.md#publish) for publishing to a IBM Planning Analytics data source is misleading and contains a typo (function name, missing "'" and  needless "/Contents").

Current code example is:
`("https://myPAconnection.PlanningAnalytics.com", "C:\path\to\local\file.xlsx",
"/tm1/Planning%20Sample/api/v1/Contents('Applications')/Contents('Planning %20Sample)/Contents", "PublishedFileName.xlsx", "My Description", "MyToolTip")`

and should be changed to:

`Publish ("https://myPAconnection.PlanningAnalytics.com", "C:\path\to\local\file.xlsx",
"/tm1/Planning%20Sample/api/v1/Contents('Applications')/Contents('Planning %20Sample')", "PublishedFileName.xlsx", "My Description", "MyToolTip")`

**Comment by charliele-ibm** [comment]
Documentation has been updated to reflect the suggested changes.
