### ISSUE TITLE
Samples are using out-of-date information

### ISSUE THREAD

**Issue by Meister1867** [IBM/paxapi#3]
Operating system: ✍️ TODO
Last upstream commit (run `git log --author="Robert Lord" | head -n 1`): ✍️ TODO
Browser version(s): ✍️ TODO
Ruby version (run `ruby -v`):  ✍️ TODO

---

✍️ TODO write your issue here
Ref. [IBM Forum link](https://community.ibm.com/community/user/businessanalytics/communities/community-home/digestviewer/viewthread?MessageKey=0d6cbff8-2031-4bbf-a409-6669427ce31a&CommunityKey=8fde0600-e22b-4178-acf5-bf4eda43146b&tab=digestviewer#bm0d6cbff8-2031-4bbf-a409-6669427ce31a)
It appears that the samples are using out-of-date values when using the REST API.  In the case the REST GET request ([link](https://ibm.github.io/paxapi/#get-requests)) the code being used is

`Public Property Get OData(Server As String) As String
    'OData endpoint
    OData = HubEndpoint + "server('" + Server + "')/api/v1"
End Property`

but as per the referred link on the forums it should use...

`Public Property Get OData(Server As String) As String
    'OData endpoint
    OData = "tm1/" + Server + "/api/v1"
End Property`

Changing the value for OData resulted in a connection being established.

**Comment by charliele** [comment]
Document updated

https://ibm.github.io/paxapi/#rest-api

Please check it out and see if it looks good.

**Comment by charliele-ibm** [comment]
https://ibm.github.io/paxapi/#rest-api

Document has been updated. Please check it out and see if it looks fine
