### ISSUE TITLE
Click Open and it jumps you to Slatedocs , a completely different GIt repository

### ISSUE THREAD

**Issue by paulsimongb** [IBM/paxapi#35]
**Bug Description**
A clear and concise description of what the bug is and how to reproduce it.

**Screenshots**

**Browser (please complete the following information):**

**Last upstream Slate commit (run `git log --author="\(Robert Lord\)\|\(Matthew Peveler\)\|\(Mike Ralphson\)" | head -n 1`):**
Put the commit hash here

**Comment by tedphillips** [comment]
If I follow, I agree - the repo issue template does need some adjustment! 
I'll work with doc to get that straightened out. 

In the meantime will get your issues reviewed - thanks for your engagement here.

**Comment by tedphillips** [comment]
i think i cleaned up the site template a bit, much thanks.
