### ISSUE TITLE
ambiguity for TI ExecuteFunction api

### ISSUE THREAD

**Issue by tedphillips** [IBM/paxapi#6]
text description says to use the reporting object

> Syntax
> The following string is the syntax for the Create method.
> 
> Reporting.ExecuteFunction(<data source URL>, <server name>, <TI process name>, <Optional TI process parameter>)

but the code sample says to use the automation object

>     'Call the Cognos Office Automation object to refresh the data.
>     CognosOfficeAutomationObject.ExecuteFunction host, server, processName, s

I believe the code sample case is accurate.

**Comment by charliele-ibm** [comment]
Thanks Ted,

I've updated the documentation.

https://ibm.github.io/paxapi/#turbointegrator-functions
